<?php

/**
 * @file
 * Main module file for Paragraphs Styles.
 *
 * @Issue(
 *   "Updated README.txt file with information related to Paragraph Styles
 *   module"
 *   type="task"
 *   priority="low"
 *   labels="documentation"
 * )
 * @Issue(
 *   "Updated paragraphs_styles_test module files to test the Paragraph Styles
 *   module"
 *   type="task"
 *   priority="low"
 *   labels="testing"
 * )
 */

// Paragraphs entity type.
define('PARAGRAPHS_STYLES_ENTITY_TYPE', 'paragraphs_item');

// Field type paragraphs styles list.
define('PARAGRAPHS_STYLES_FIELD_TYPE_LIST', 'paragraphs_styles');

// Include fields.
require_once dirname(__FILE__) . '/includes/paragraphs_styles.fields.inc';


/**
 * Hooks.
 */

/**
 * Implements template_preprocess_entity()
 *
 * @Issue(
 *   "Adding classes per style should be optional via a configuration variable"
 *   type="improvement"
 *   priority="low"
 *   labels="administration, configuration"
 * )
 */
function paragraphs_styles_preprocess_entity(&$variables) {
  if ($variables['entity_type'] !== PARAGRAPHS_STYLES_ENTITY_TYPE) {
    return;
  }

  $styles = paragraphs_styles_get_styles($variables['paragraphs_item']);
  foreach ($styles as $style) {
    $variables['classes_array'][] = drupal_html_class('paragraphs_styles_' . $style);
  }
}


/**
 * Public API.
 */

/**
 * Get list of options from other modules.
 *
 * @param $field
 * @param $instance
 * @return array
 */
function paragraphs_styles_get_options($field, $instance) {
  $options = array();
  $options = module_invoke_all('paragraphs_styles_list_options', $options, $field, $instance);
  drupal_alter('paragraphs_styles_list_options', $options);

  return $options;
}

/**
 * Get styles from a paragraph item.
 *
 * @param ParagraphsItemEntity $item
 * @return string
 */
function paragraphs_styles_get_styles(ParagraphsItemEntity $item) {
  $styles = array();
  $instances = field_info_instances(PARAGRAPHS_STYLES_ENTITY_TYPE, $item->bundle);

  foreach ($instances as $instance) {
    $field_name = $instance['field_name'];
    $field = field_info_field($field_name);

    if ($field['type'] == PARAGRAPHS_STYLES_FIELD_TYPE_LIST) {
      // Determine the list of languages to iterate on.
      $languages = field_available_languages(PARAGRAPHS_STYLES_ENTITY_TYPE, $field);

      foreach ($languages as $langcode) {
        if (!empty($item->{$field_name}[$langcode])) {
          foreach ($item->{$field_name}[$langcode] as $field_item) {
            $styles[] = $field_item['value'];
          }
        }
      }
    }
  }

  return $styles;
}
